name: build_deploy_aks

on:
  push:
    branches:
      - main
    paths:
      - 'aks-node/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: aks-demo
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3

      - name: Azure login
        id: login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: '${{ secrets.resource_group }}' 
          cluster-name: '${{ secrets.cluster_name }}'

      - name: Docker login to ACR
        run: |
            az acr login --name ${{ secrets.registry }}

      - name: Build and push Docker image
        run: |
            docker build -t ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/myapp:${{ github.sha }} .
            docker push ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/myapp:${{ github.sha }}
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to AKS
        id: deploy-aks
        uses: azure/k8s-deploy@v1
        with:
          namespace: 'default'
          manifests: |
            K8s/deployment.yaml
          images: |
            ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/myapp:${{ github.sha }}