name: build_deploy_aks

on:
  push:
    branches:
      - main
    paths:
      - 'aks-node/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: aks-demo
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3

      - name: Azure login
        id: login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login to ACR
        run: |
            az acr login --name ${{ secrets.registry }}

      - name: Build and push Docker image
        run: |
            docker build -t ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/myapp:${{ github.sha }} .
            docker push ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/myapp:${{ github.sha }}
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: aks-demo
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
      
      - name: Azure login
        id: login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: '${{ secrets.resource_group }}' 
          cluster-name: '${{ secrets.cluster_name }}'

      - name: Get ACR credentials
        id: get-acr-credentials
        run: |
          echo "::set-output name=acr_password::$(az acr credential show --name ${{ secrets.registry }} --query passwords[0].value)"

      - name: Create Kubernetes secret
        run: |
          kubectl create secret docker-registry demox --docker-server=${{ secrets.registry }}.azurecr.io --docker-username=${{ secrets.registry }} --docker-password=${{ steps.get-acr-credentials.outputs.acr_password }}

      - name: Deploy to AKS
        id: deploy-aks
        uses: azure/k8s-deploy@v1
        with:
          namespace: 'default'
          manifests: |
            k8s/deployment.yaml
          images: |
            ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/myapp:${{ github.sha }}
