name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'aks-node/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: aks-demo
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Login to Azure Container Registry
        uses: docker/login-action@v3.1.0 
        with:
            registry: ${{ secrets.registry }}.azurecr.io
            username: ${{ secrets.AZURE_USERNAME }}
            password: ${{ secrets.AZURE_PASSWORD }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
            context: .
            push: true
            tags: ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/myapp:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: aks-demo
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: '${{ secrets.resource_group }}' 
          cluster-name: '${{ secrets.cluster_name }}'

      - name: Deploy to AKS
        uses: azure/k8s-deploy@v1
        with:
          namespace: 'aksdemo'
          manifests: |
            k8s/deployment.yaml
          images: |
            ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/myapp:${{ github.sha }}
